[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# disable `cargo publish`
publish = false
# disable GitHub/Gitea releases
git_release_enable = false
# create a git tag for the new package version
git_tag_enable = true
